-- Migration: 003_harvested_signals (down)
-- Intentionally empty.
-- 003 is a BASELINE: it reproduces a table that already existed in the running
-- database (656+ rows at the time of writing). It introduces nothing on an
-- existing database, so its correct reversal is to do nothing. DROP TABLE here
-- would destroy data that predates the migration — forbidden by FR-027.
--
-- See specs/004-relational-spine/contracts/migrations.md ("Baselines are a
-- deliberate exception").
