# Workers mapping - name as key, ID as value
WORKERS = {
    "Alia Ayya": "712020:66fed40e-a999-406a-a1e9-58e2347474ac",
    "Arista Prasandha": "712020:68976ad4-7f9f-4fd7-b6f1-0dd9af89ce12",
    "Anggit Rigen Mandegani": "712020:7ffdc0ec-3856-450c-a1b1-adbfb2605154",
    "Defi Priana": "712020:5f3e2f3b-6f3b-4e2e- ninetyf-1c4b8e2e5c3d",
    "Farah Qurrotu Aini": "712020:d882eb3f-72b2-435a-bc7b-396ed719b33b",
    "Halimatudz Dzakiyah": "712020:aca16589-e25b-416f-b295-fe663315a99d",
    "Nathaniella Dwi Arthanti": "712020:d1149fc3-0a52-4277-a83b-3ef564cb889b",
    "Noktah Inovasi Teknologi": "712020:5f41db40-76d3-400a-a78a-df5dc433c8cc",
    "Saladin Abdul Tawaab Al Aziz": "712020:e9225fd2-2f84-41da-8a84-d68ff48f2aa0",
    "Siti Nurhayati": "712020:c4884994-9302-4d63-bc22-513656d41516",
}

# Components mapping - name as key, ID as value
COMPONENTS = {
    "Balakosa Rewind and Play": "10034",
    "Ecky Dental Center": "10000",
    "Gudang Karung Jumbo Sidoarjo": "10010",
    "Kabin Event Organizer": "10003",
    "Karsa Studio": "10099",
    "Klinik Mata Bireuen": "10101",
    "Klinik Mata Boyolali": "10008",
    "Klinik Mata Jogja": "10068",
    "Klinik Mata Sampang": "10006",
    "Klinik Spesialis Langsa": "10033",
    "Klinik Utama Gresik": "10007",
    "Klinik Utama Sumenep": "10005",
    "LASIK Asyik by SMEC Tebet": "10009",
    "Nirwana Coffee Space Pamekasan": "10002",
    "Nirwana Coffee Space Sumenep": "10001",
    "Pelita Delapan": "10100",
    "Qur'anic Integrated School of Muhammadiyah (QISMu)": "10004",
    "RS Mata SMEC Balikpapan": "10067",
    "RS Mata SMEC Medan": "10102",
    "Satoe Rock Steak": "10066",
    "dr. Tommy": "10135",
    "ORM JBB Pertamina PN": "10136",
    "Persada Darul Ulum": "10137",
    "Bahari Sentosa Abadi": "10138",
    "Klinik Utama Gasa": "10139",
}

# Content Editor mapping - client name as key, worker name as value
CONTENT_EDITOR = {
    "Klinik Mata Boyolali": "Nathaniella Dwi Arthanti",
    "Kabin Event Organizer": "Nathaniella Dwi Arthanti",
    "Ecky Dental Center": "Nathaniella Dwi Arthanti",
    "Gudang Karung Jumbo Sidoarjo": "Nathaniella Dwi Arthanti",
    "Klinik Mata Bireuen": "Alia Ayya",
    "Klinik Utama Gresik": "Alia Ayya",
    "LASIK Asyik by SMEC Tebet": "Noktah Inovasi Teknologi",
    "Bahari Sentosa Abadi": "Anggit Rigen Mandegani",
    "Balakosa Rewind and Play": "Alia Ayya",
    "Nirwana Coffee Space Pamekasan": "Anggit Rigen Mandegani",
    "Pelita Delapan": "Anggit Rigen Mandegani",
    "Nirwana Coffee Space Sumenep": "Alia Ayya",
    "Klinik Utama Gasa": "Nathaniella Dwi Arthanti",
    "Klinik Utama Sumenep": "Saladin Abdul Tawaab Al Aziz",
    "Karsa Studio": "Saladin Abdul Tawaab Al Aziz",
    "Klinik Spesialis Langsa": "Saladin Abdul Tawaab Al Aziz",
    "Klinik Mata Sampang": "Saladin Abdul Tawaab Al Aziz",
    "Klinik Mata Jogja": "Anggit Rigen Mandegani",
    "RS Mata SMEC Medan": "Noktah Inovasi Teknologi",
    "RS Mata SMEC Balikpapan": "Anggit Rigen Mandegani",
    "dr. Tommy": "Noktah Inovasi Teknologi",
    "ORM JBB Pertamina PN": "Noktah Inovasi Teknologi",
    "Persada Darul Ulum": "Noktah Inovasi Teknologi",
}

# Field Associate mapping - client name as key, worker name as value
FIELD_ASSOCIATE = {
    "Gudang Karung Jumbo Sidoarjo": "Farah Qurrotu Aini",
    "Bahari Sentosa Abadi": "Farah Qurrotu Aini",
    "Klinik Utama Gresik": "Farah Qurrotu Aini",
    "Klinik Mata Sampang": "Farah Qurrotu Aini",
    "Persada Darul Ulum": "Farah Qurrotu Aini",
    "Klinik Mata Bireuen": "Farah Qurrotu Aini",
    "Klinik Spesialis Langsa": "Farah Qurrotu Aini",
    "ORM JBB Pertamina PN": "Halimatudz Dzakiyah",
    "dr. Tommy": "Halimatudz Dzakiyah",
    "Klinik Mata Boyolali": "Halimatudz Dzakiyah",
    "Klinik Mata Jogja": "Halimatudz Dzakiyah",
    "LASIK Asyik by SMEC Tebet": "Halimatudz Dzakiyah",
    "RS Mata SMEC Medan": "Halimatudz Dzakiyah",
    "RS Mata SMEC Balikpapan": "Halimatudz Dzakiyah",
    "Kabin Event Organizer": "Siti Nurhayati",
    "Ecky Dental Center": "Siti Nurhayati",
    "Balakosa Rewind and Play": "Siti Nurhayati",
    "Nirwana Coffee Space Pamekasan": "Siti Nurhayati",
    "Pelita Delapan": "Siti Nurhayati",
    "Nirwana Coffee Space Sumenep": "Siti Nurhayati",
    "Klinik Utama Gasa": "Siti Nurhayati",
    "Klinik Utama Sumenep": "Siti Nurhayati",
    "Karsa Studio": "Siti Nurhayati",
}
